version: "1.0"

networks:
  delectric-network:
    driver: bridge

volumes:
  delectricdb-vol:

services:
  #######################################
  # Mysql: The database used by all
  #######################################
  Delectric-mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
    volumes:  
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./init-scripts/my.cnf:/etc/mysql/conf.d/my.cnf # Set config file to adjust timezone to SGT
    networks:
      - delectric-network
  
  #######################################
  # Charging Station Microservice
  #######################################
  # delectric-charging-station:
  #   build:
  #     context: ./charging-station
  #   ports:
  #     - "5001:5001"
  #   depends_on:
  #     - Delectric-mysql
  #   environment:      
  #     - dbURL=mysql+mysqlconnector://${DB_USER}:${DB_USER_PASSWORD}@Delectric-mysql:3306/chargingstationdb # Pointed to chargingstationdb
  #   networks:
  #     - delectric-network